# Generated by Django 3.2.12 on 2022-02-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=64)),
                ('state', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'Work in progress'), ('pending', 'Pending validation')], default='completed', max_length=64)),
                ('linked_epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic', to='epics.epic')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=64)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='epics.epic')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=64)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug', to='epics.epic')),
            ],
        ),
    ]
