# Generated by Django 3.2.12 on 2022-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0002_alter_epic_linked_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(default=' ', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='title',
            field=models.CharField(default=' ', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default=' ', max_length=64, unique=True),
        ),
    ]
