# Generated by Django 3.2.12 on 2022-02-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0003_auto_20220215_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='epic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug', to='epics.epic'),
        ),
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='epics.epic'),
        ),
    ]
